
const PLAYER_TEAM_MAP = {
    /*** SEASON 6 ***/
    "kawa": "KFC",
    "AwesomeX": "MCDONALDS",
    "awesomex": "MCDONALDS",
    "JR": "PANDA EX",
    "jr": "PANDA EX",
    "dethorne": "KFC",
    "elffaW": "LONG JOHN",
    "elffaw": "LONG JOHN",
    "andy mac": "MCDONALDS",
    "Andy Mac": "MCDONALDS",
    "Twerp": "DAIRY QUEEN",
    "twerp": "DAIRY QUEEN",
    "bill": "DAIRY QUEEN",
    "mattaux": "HOOTERS",
    "kawa2796": "KFC",
    "Kawa2796": "KFC",
    "pnkrockjock26": "MCDONALDS",
    "Hootenannies": "HOOTERS",
    "hootenannies": "HOOTERS",
    "ofthemoon16": "LONG JOHN",
    "GolfJBC89": "TACO BELL",
    "golfjbc89": "TACO BELL",
    "JMyrv": "LONG JOHN",
    "jmyrv": "LONG JOHN",
    "Kurtzy P00": "DAIRY QUEEN",
    "kurtzy P00": "DAIRY QUEEN",
    "KURTZYP00": "DAIRY QUEEN",
    "KURTZY P00": "DAIRY QUEEN",
    "snakes on a microplane": "DAIRY QUEEN",
    "Evergreen6258": "HOOTERS",
    "evergreen6258": "HOOTERS",
    "madscoutfan": "PANDA EX",
    "madscout": "PANDA EX",
    "CREAM DADDY9057": "DAIRY QUEEN",
    "cream daddy9057": "DAIRY QUEEN",
    "creamdaddy9057": "DAIRY QUEEN",
    "nkssoccer15": "TACO BELL",
    "fatkiddestroyers": "TACO BELL",
    "tfeej": "PANDA EX",
    "TFeej": "PANDA EX",
    "ades 35": "FAMOUS D",

    // one night sub
    "phelpsjr8": "PANDA EX",

    /*** SEASON 5 ***/
    // "kawa": "TOAST",
    // "AwesomeX": "BRAN",
    // "awesomex": "BRAN",
    // "JR": "SMACKS",
    // "jr": "SMACKS",
    // "dethorne": "CRUNCH",
    // "elffaW": "SMACKS",
    // "elffaw": "SMACKS",
    // "andy mac": "TRIX",
    // "Andy Mac": "TRIX",
    // "Twerp": "FROOTS",
    // "twerp": "FROOTS",
    // "mattaux": "CHARMS",
    // "kawa2796": "BRAN",
    // "Kawa2796": "BRAN",
    // "pnkrockjock26": "KRISPIES",
    // "Hootenannies": "KRISPIES",
    // "hootenannies": "KRISPIES",
    // "ofthemoon16": "CHEERIOS",
    // "GolfJBC89": "FROOTS",
    // "golfjbc89": "FROOTS",
    // "JMyrv": "CHEERIOS",
    // "jmyrv": "CHEERIOS",
    // "Kurtzy P00": "TOAST",
    // "kurtzy P00": "TOAST",
    // "KURTZYP00": "TOAST",
    // "KURTZY P00": "TOAST",
    // "snakes on a microplane": "FLAKES",
    // "Evergreen6258": "TRIX",
    // "evergreen6258": "TRIX",
    // "madscoutfan": "CHARMS",
    // "madscout": "CHARMS",
    // "CREAM DADDY9057": "TOAST",
    // "cream daddy9057": "TOAST",
    // "creamdaddy9057": "TOAST",
    // "nkssoccer15": "CRUNCH",
    // "fatkiddestroyers": "FLAKES",

    /*** SEASON 4 ***/
    // "kawa": "Pilgrims",
    // "JR": "Reindeer",
    // "jr": "Reindeer",
    // "dethorne": "Team Santa",
    // "elffaW": "Turkeys",
    // "elffaw": "Turkeys",
    // "andy mac": "Reindeer",
    // "Andy Mac": "Reindeer",
    // "Twerp": "Pumpkins",
    // "twerp": "Pumpkins",
    // "mattaux": "Pumpkins",
    // "kawa2796": "Pilgrims",
    // "Kawa2796": "Pilgrims",
    // "pnkrockjock26": "Pumpkins",
    // "Hootenannies": "Pilgrims",
    // "hootenannies": "Pilgrims",
    // "ofthemoon16": "Death",
    // "GolfJBC89": "Turkeys",
    // "golfjbc89": "Turkeys",
    // "JMyrv": "Turkeys",
    // "jmyrv": "Turkeys",
    // "Kurtzy P00": "Team Santa",
    // "kurtzy P00": "Team Santa",
    // "KURTZYP00": "Team Santa",
    // "KURTZY P00": "Team Santa",
    // "snakes on a microplane": "Reindeer",
    // "Evergreen6258": "Team Santa",
    // "evergreen6258": "Team Santa",
    // "madscoutfan": "Death",
    // "madscout": "Death",
    // "Gnomie, dont ya know me?": "Death",
    // "gnomie, dont ya know me?": "Death",
    // "CREAM DADDY9057": "Team Santa",
    // "cream daddy9057": "Team Santa",
    // "creamdaddy9057": "Team Santa",


    /*** SEASON 3 ***/
    // "kawa": "Crabs",
    // "JR": "Crabs",
    // "dethorne": "LongBows",
    // "elffaW": "LongBows",
    // "Andy Mac": "Queens",
    // "Twerp": "LongBows",
    // "mattaux": "Samurai",
    // "kawa2796": "Samurai",
    // "Kawa2796": "Samurai",
    // "pnkrockjock26": "Queens",
    // "Hootenannies": "Pigeons",
    // "ofthemoon16": "Pigeons",
    // "AwesomeX": "Knights",
    // "GolfJBC89": "Samurai",
    // "JMyrv": "Knights",
    // "jmyrv": "Knights",
    // "Elissa": "Crabs",
    // "Kurtzy P00": "Knights",
    // "KURTZYP00": "Knights",
    // "snakes on a microplane": "Queens",
    // "Evergreen6258": "Pigeons",
    // "madscoutfan": "N00BS",
    // "Gnomie, dont ya know me?": "N00BS",

    // BOTSBOTS unless there is a team with bots
    "squall": "FAMOUS D",
    "shepard": "FAMOUS D",
    "storm": "FAMOUS D",
    "beast": "FAMOUS D",
    "cougar": "FAMOUS D",
    "viper": "FAMOUS D",
    "tex": "FAMOUS D",
    "heater": "FAMOUS D",
    "sticks": "FAMOUS D",
    "raja": "FAMOUS D",
    "sabertooth": "FAMOUS D",
    "merlin": "FAMOUS D",
    "storm": "FAMOUS D",
    "myrtle": "FAMOUS D",
    "casper": "FAMOUS D",
    "armstrong": "FAMOUS D",
    "Foamer": "FAMOUS D",
    "samara": "FAMOUS D",
    "iceman": "FAMOUS D",
    "marley": "FAMOUS D",
    "rainmaker": "FAMOUS D",
    "roundhouse": "FAMOUS D",
    "dude": "FAMOUS D",
    "stinger": "FAMOUS D",
    "maverick": "FAMOUS D",
    "chipper": "FAMOUS D",
    "rex": "FAMOUS D",
    "slider": "FAMOUS D",
    "buzz": "FAMOUS D",
    "imp": "FAMOUS D",
    "wolfman": "FAMOUS D",
    "mountain": "FAMOUS D",
    "centice": "FAMOUS D",
    "junker": "FAMOUS D",
    "khan": "FAMOUS D",
    "caveman": "FAMOUS D",
    "hollywood": "FAMOUS D",
    "saltie": "FAMOUS D",
    "poncho": "FAMOUS D",
    "boomer": "FAMOUS D",
    "gerwin": "FAMOUS D",
    "outlaw": "FAMOUS D",
    "foamer": "FAMOUS D",
    "bandit": "FAMOUS D",
    "scout": "FAMOUS D",
    "swabbie": "FAMOUS D",
    "goose": "FAMOUS D",
    "yuri": "FAMOUS D",
    "sultan": "FAMOUS D",
};

const PLAYER_RLNAME_MAP = {
    "kawa": "Kawa",
    "JR": "JR",
    "jr": "JR",
    "dethorne": "PDT",
    "elffaW": "Mike",
    "elffaw": "Mike",
    "Andy Mac": "Andy",
    "andy mac": "Andy",
    "Twerp": "Billy",
    "twerp": "Billy",
    "bill": "Billy",
    "mattaux": "M Aux",
    "kawa2796": "Mark K",
    "Kawa2796": "Mark K",
    "pnkrockjock26": "TC",
    "Hootenannies": "Shanley",
    "hootenannies": "Shanley",
    "ofthemoon16": "Jay",
    "AwesomeX": "Dan Bot",
    "awesomex": "Dan Bot",
    "GolfJBC89": "Cohn",
    "golfjbc89": "Cohn",
    "JMyrv": "Myrv",
    "jmyrv": "Myrv",
    "Elissa": "Elissa",
    "elissa": "Elissa",
    "Kurtzy P00": "Tom",
    "kurtzy p00": "Tom",
    "KURTZYP00": "Tom",
    "KURTZY P00": "Tom",
    "snakes on a microplane": "Speder",
    "Evergreen6258": "Matt H",
    "evergreen6258": "Matt H",
    "madscoutfan": "Eliot",
    "madscout": "Eliot",
    "Gnomie, dont ya know me?": "Max",
    "gnomie, dont ya know me?": "Max",
    "CREAM DADDY9057": "Tom",
    "cream daddy9057": "Tom",
    "Cream Daddy9057": "Tom",
    "creamdaddy9057": "Tom",
    "nkssoccer15": "Nimish",
    "fatkiddestroyers": "Vinny",
    "tfeej": "Tom 3.0",
    "TFeej": "NEW",
    "ades 35": "Dave"
};

module.exports = { PLAYER_RLNAME_MAP, PLAYER_TEAM_MAP };
